version: "3.7"
services:
  # production database
  # OLTP
  db:
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    ports:
      - 3306:3306
    volumes:
      - c:\docker\data-pipeline\db:/var/lib/mysql
      - ./db:/usr/src/db
    environment:
      - MYSQL_DATABASE=data_pipeline
      - MYSQL_ROOT_PASSWORD=password

  # data-warehouse
  # OLAP
  data-warehouse:
    image: guildeducation/docker-amazon-redshift
    restart: always
    ports:
      - 5439:5439
    volumes:
      - ./data-warehouse:/usr/src/data-warehouse
    environment:
      - POSTGRES_PASSWORD=password

  storage:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001" 
    restart: always
    volumes:
      - c:\docker\data-pipeline\storage:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password

  app:
    build: app
    restart: always
    stdin_open: true
    tty: true 
    volumes:
      - ./app:/usr/src/app

volumes:
  app: